CREATE USER C##temporal IDENTIFIED BY temporal CONTAINER=ALL;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE TO C##temporal;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO C##temporal;
GRANT UNLIMITED TABLESPACE TO C##temporal;

-- Exit with success status
EXIT;